### ISSUE TITLE
Prism-Catel-Syncfusion !

### ISSUE THREAD

**Issue by Aitania** [Ales999/TestPrismCatelJ#1]
Hallo Alexey,

I  use Syncfusion as well. I find you have implement a very nice sample.
Is it possible to load the Modules dynamically?
I have created a button-command for each Modul.

![dynamically_load](https://user-images.githubusercontent.com/4704114/27536221-8b4215d4-5a6e-11e7-9cc2-48f7a442fedd.PNG)

Why the syncfusion:DockingManager does not fill the whole Shell?

Regards,
Michael

**Comment by Ales999** [comment]
Hello Michael.
This code is very old, Probably there were changes in the libraries that are not obvious.
This is my compilation at that time:
![2017-06-26 16 07 50](https://user-images.githubusercontent.com/367257/27536801-25e96176-5a8a-11e7-8e23-1ea96933baed.png)

The original project is working for you?

**Comment by Ales999** [comment]
Am update to last master, check this.
It corresponds to the picture above.

And dynamic loading by me then was not considered for this example.
I just started to be interested in this topic, but Prim can download modules, although I have not tried it yet.

**Comment by Ales999** [comment]
Possible helped [this](https://translate.google.ru/translate?sl=ru&tl=en&js=y&prev=_t&hl=ru&ie=UTF-8&u=https%3A%2F%2Fhabrahabr.ru%2Fpost%2F271655%2F&edit-text=&act=url) translate (from Russian ) with analog you project

**Comment by Aitania** [comment]
Hallo Alexey,
thank you for the quick answer. 
I could managed to run your old sample. Your new sample is running as well.
I try since some days to find a solution to load modules dynamically into a Orchestra-Shell.
https://github.com/WildGums/Orchestra/issues/49
https://github.com/WildGums/Orchestra/issues/72

Loading module/view dynamically and composite the UI (MainRegion, Shell, StatusBar) by
1. Loading less modules to memory on startup,
2. load only **selected** modules from backstage button in Ribbon. Thats why i have changed your   sample with buttons. One for each module. Is it possible to extend your sample and load dynamically the selected module in MainRegion?

With this in mind application can be built with many numbers of modules placed in some central place that can be dynamically loaded and then list then in app – for example after application start ribbon can be listed with modules list (for example button per module) – when user chose to show module its dll will be downloaded and displayed in some control (for example in DockingManager).

I have low experiance with Prism. 
Geert recommend to use these libraries:
    Orchestra
    Orc.Extensibility for module detection / plugins
    Orc.Prism if you need regions (but we don't use this ourselves, we create our own TabHost that plugins can interact with)

I can explain some details if they are not clear. Any help will be welcome !!!
Helpfull links:
https://catelproject.atlassian.net/wiki/display/CTL45/Catel.Extensions.Prism
https://help.syncfusion.com/wpf/ribbon/patternsandpractices
I am interesting in a sollusion with Orc.Extensibility... But there is not Documentation or samples... :-(
https://github.com/WildGums/Orc.Extensibility

**Comment by Ales999** [comment]
Hello Michael.

My programming is small hobby, A'm not best c# programmer.
I agree, Orestra - very little information, and I did not use it.
As far as I understand you need a "Lazy Pattern".
Prism support MEF, possible need you.
Pay attention to this article:  [The Simplest Way to use MEF Fully Lazy DLL Loading](https://www.codeproject.com/Articles/497626/The-Simplest-Way-to-use-MEF-Fully-Lazy-DLL-Loadi) 

Maybe:
Next, for get list modules, possible needed 'temp Appdomain for Assembly.ReflectionOnlyLoad(string)'
After using, and get Modules name, unload temp appdomain.
Example for load modules into  AppDomain, this: https://www.codeproject.com/Articles/453778/Loading-Assemblies-from-Anywhere-into-a-New-AppDom

PS
Recommend read Books: [Dependency Injection in .NET](https://www.amazon.com/Dependency-Injection-NET-Mark-Seemann/dp/1935182501/ref=sr_1_1?s=books&ie=UTF8&qid=1364898875&sr=1-1&keywords=dependency+injection+in+.net)

**Comment by Aitania** [comment]
Hallo Alexey,

Thank you for your comments. 
I think i will use Catel and Prism, since Orchestra does not support modularity.

**Comment by Ales999** [comment]
Do you need to dynamically load DLL or just run out of work on demand?

**Comment by Ales999** [comment]
Possible to you project: https://msdn.microsoft.com/en-us/magazine/dn519924.aspx
Do you need to dynamically load DLL or just run out of work on demand?
